export const NOTES_CREATE = "NOTES_CREATE";
export const NOTES_DELETE = "NOTES_DELETE";
export const NOTES_EDIT = "NOTES_EDIT";
export const NOTES_LOADING = "NOTES_LOADING";

export const MODAL_ACTIVE = "MODAL_ACTIVE";
export const MODAL_CLOSE = "MODAL_CLOSE";
export const MODAL_SETCONTENT = "MODAL_SETCONTENT";
export const MODAL_ONCHANGETITLE = "MODAL_ONCHANGETITLE";
export const MODAL_ONCHANGEDESCRIPTION = "MODAL_ONCHANGEDESCRIPTION";
